### ISSUE TITLE
Ship rails-bin upstream

### ISSUE THREAD

**Issue by zzak** [skipkayhil/rail_inspector#1]
The goal is to be able to install this project as and run the tests locally as well.

For example, when developing on Rails and making changes to the [configuring guide](https://guides.rubyonrails.org/configuring.html), breaking changes will fail the build in CI.

This is great to be able to prevent shipping incorrect documentation, and also providing developers feedback on their work.

However, it would be nice if a developer could execute those same tests locally without having to run a build.

---

If we make this project a gem, and add it to the rails/rails `Gemfile` we could have a rake task to run the same tests for us.

```
cd ~/oss/rails
bundle exec rake check-changelogs
```

This would require the following work:

1. We ship this project as a gem
2. Add that gem to rails/rails `Gemfile`
3. Update rails/rails `Rakefile` to include any tasks we want to make available

The first part is simple, the second part requires getting buy-in from other Rails committers. :pray:

**Comment by skipkayhil** [comment]
Done in rails/rails#48216 🎉
